/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_projekat10_MyNDK */

#ifndef _Included_com_example_projekat10_MyNDK
#define _Included_com_example_projekat10_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_projekat10_MyNDK
 * Method:    promeni
 * Signature: (DZ)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_projekat10_MyNDK_promeni
  (JNIEnv *, jobject, jdouble, jboolean);

#ifdef __cplusplus
}
#endif
#endif
